export const columns = [
  {
    dataKey: 'styleName',
    title: 'Style',
    inputType: 'text-input'
  },
  {
    dataKey: 'state',
    title: 'Status'
  },
  {
    dataKey: 'label',
    title: 'Label',
    inputType: 'text-input'
  },
  {
    dataKey: 'styleColor',
    title: 'Color',
    inputType: 'text-input'
  },
  {
    dataKey: 'fit',
    title: 'Fit/Block',
    inputType: 'text-input'
  },
  {
    dataKey: 'millName',
    title: 'Mill'
  },
  {
    dataKey: 'fabPlacement',
    title: 'Fab. Placement',
    inputType: 'text-input'
  },
  {
    dataKey: 'fabType',
    title: 'Fab. Type'
  },
  {
    dataKey: 'fabComposition',
    title: 'Fab. Composition',
    inputType: 'text-input'
  },
  {
    dataKey: 'csv',
    title: 'CSV'
  },
  {
    dataKey: 'width',
    title: 'Cuttable \nWidth (CM)',
    inputType: 'text-input',
    options: {
      type: 'number'
    }
  },
  {
    dataKey: 'repeats',
    title: 'Repeats (CM)'
  },
  {
    dataKey: 'fabDirection',
    title: 'Fab. \nDirection'
  },
  {
    dataKey: 'wash',
    title: 'Wash'
  },
  {
    dataKey: 'shrinkage',
    title: 'Shrinkage'
  },
  {
    dataKey: 'layCu',
    title: 'Costing CU \nby CAD'
  },
  {
    dataKey: 'bomCu',
    title: 'BOM CU \nby CAD'
  },
  {
    dataKey: 'wastage',
    title: 'Wastage & \nBuffer (%)'
  },
  {
    dataKey: 'finalCu',
    title: 'Final \nCosting CU'
  }
]

export const rows = [
  {
    id: 41,
    mill: null,
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 2,
      modifiedAt: 1588750085099,
      lastModifiedBy: 'su_dev',
      name: 'Piece Dyed',
      desc: null,
      uid: 'FabricCategory-Piece Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 10,
    state: 'New',
    buyerPO: null,
    internalPO: null,
    label: null,
    styleName: null,
    styleColor: null,
    fit: null,
    fabArticle: 'ART-113',
    fabComposition: '98/2 Cotton Elastane ',
    fabPlacement: 'INNER COLLAR BAND + SIDE SEAM TRIANGLE PATCH',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{}',
    total: null,
    millId: null,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    sortField: 'CLASSIC-No-139.7-BODY-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 42,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 4,
      modifiedAt: 1588750296825,
      lastModifiedBy: 'su_dev',
      name: 'Printed',
      desc: null,
      uid: 'FabricType-Printed',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 11,
    state: 'New',
    buyerPO: null,
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 10',
    styleColor: 'Blue Depth',
    fit: 'SLIM',
    fabArticle: 'ART-114',
    fabComposition: '100% Cotton ',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'NO',
    width: 144.78,
    repeatLength: 1.65,
    repeatWidth: 2.03,
    warpShrinkage: 1,
    weftShrinkage: 1,
    remarks: 'Test Remarks',
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":2},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Printed',
    millName: 'Arvind',
    sortField: 'SLIM-No-144.78-ALL OVER GARMENT-All garment one-way-1-1-1.65-2.03',
    repeats: '1.65 x 2.03',
    shrinkage: 'L+1.00% W+1.00'
  },
  {
    id: 39,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 9,
    state: 'New',
    buyerPO: '5',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 8',
    styleColor: 'Bright white',
    fit: 'SLIM',
    fabArticle: 'ART-111',
    fabComposition: '98% COTTON 2% SPANDEX',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":3},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    millName: 'Arvind',
    sortField: 'SLIM-No-129.54-ALL OVER GARMENT-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 36,
    mill: null,
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 2,
      modifiedAt: 1588750085099,
      lastModifiedBy: 'su_dev',
      name: 'Piece Dyed',
      desc: null,
      uid: 'FabricCategory-Piece Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 6,
    state: 'New',
    buyerPO: null,
    internalPO: null,
    label: null,
    styleName: null,
    styleColor: null,
    fit: null,
    fabArticle: 'ART-108',
    fabComposition: '98/2 Cotton Elastane ',
    fabPlacement: 'INNER COLLAR BAND + SIDE SEAM TRIANGLE PATCH',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{}',
    total: null,
    millId: null,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    sortField: 'CLASSIC-No-139.7-BODY-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 37,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 7,
    state: 'New',
    buyerPO: '6',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 7',
    styleColor: 'Noon Blue',
    fit: 'SLIM',
    fabArticle: 'ART-109',
    fabComposition: '98% COTTON 2% SPANDEX',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":2},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    millName: 'Arvind',
    sortField: 'SLIM-No-129.54-ALL OVER GARMENT-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 38,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 8,
    state: 'New',
    buyerPO: '6',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 7',
    styleColor: 'Blue Depth',
    fit: 'SLIM',
    fabArticle: 'ART-110',
    fabComposition: '98% COTTON 2% SPANDEX',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":2},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    millName: 'Arvind',
    sortField: 'SLIM-No-129.54-ALL OVER GARMENT-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 40,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 10,
    state: 'New',
    buyerPO: '5',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 9',
    styleColor: 'Allure',
    fit: 'CLASSIC',
    fabArticle: 'ART-112',
    fabComposition: '97/3 Cotton/Spandex',
    fabPlacement: 'BODY',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 139.7,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":3},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    millName: 'Arvind',
    sortField: 'CLASSIC-No-139.7-BODY-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 34,
    mill: null,
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 2,
      modifiedAt: 1588750085099,
      lastModifiedBy: 'su_dev',
      name: 'Piece Dyed',
      desc: null,
      uid: 'FabricCategory-Piece Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 5,
    state: 'New',
    buyerPO: null,
    internalPO: null,
    label: null,
    styleName: null,
    styleColor: null,
    fit: null,
    fabArticle: 'ART-106',
    fabComposition: '98/2 Cotton Elastane ',
    fabPlacement: 'INNER COLLAR BAND + SIDE SEAM TRIANGLE PATCH',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{}',
    total: null,
    millId: null,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    sortField: 'CLASSIC-No-139.7-BODY-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 35,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 6,
    state: 'New',
    buyerPO: '4',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 6',
    styleColor: 'Allure',
    fit: 'CLASSIC',
    fabArticle: 'ART-107',
    fabComposition: '97/3 Cotton/Spandex',
    fabPlacement: 'BODY',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 139.7,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":3},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    millName: 'Arvind',
    sortField: 'CLASSIC-No-139.7-BODY-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 30,
    mill: null,
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 2,
      modifiedAt: 1588750085099,
      lastModifiedBy: 'su_dev',
      name: 'Piece Dyed',
      desc: null,
      uid: 'FabricCategory-Piece Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 2,
    state: 'New',
    buyerPO: null,
    internalPO: null,
    label: null,
    styleName: null,
    styleColor: null,
    fit: null,
    fabArticle: 'ART-102',
    fabComposition: '98/2 Cotton Elastane ',
    fabPlacement: 'INNER COLLAR BAND + SIDE SEAM TRIANGLE PATCH',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{}',
    total: null,
    millId: null,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    sortField: 'CLASSIC-No-129.54-ALL OVER GARMENT-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 32,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 4,
      modifiedAt: 1588750296825,
      lastModifiedBy: 'su_dev',
      name: 'Printed',
      desc: null,
      uid: 'FabricType-Printed',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 4,
    state: 'New',
    buyerPO: '3',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 4',
    styleColor: 'Windsurf Blue',
    fit: 'SLIM',
    fabArticle: 'ART-104',
    fabComposition: '97/3 Cotton Spandex',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'NO',
    width: 139.7,
    repeatLength: 0.2,
    repeatWidth: null,
    warpShrinkage: 1,
    weftShrinkage: 1,
    remarks: 'Test Remarks',
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":2},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Printed',
    millName: 'Arvind',
    sortField: 'SLIM-No-139.7-ALL OVER GARMENT-All garment one-way-1-1-0.2-0',
    repeats: '0.2',
    shrinkage: 'L+1.00% W+1.00'
  },
  {
    id: 33,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 5,
    state: 'New',
    buyerPO: '4',
    internalPO: null,
    label: 'L1',
    styleName: 'Style 5',
    styleColor: 'Black',
    fit: 'CLASSIC',
    fabArticle: 'ART-105',
    fabComposition: '97/3 Cotton/Spandex',
    fabPlacement: 'BODY',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 139.7,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":3},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    millName: 'Arvind',
    sortField: 'CLASSIC-No-139.7-BODY-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 31,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 4,
      modifiedAt: 1588750296825,
      lastModifiedBy: 'su_dev',
      name: 'Printed',
      desc: null,
      uid: 'FabricType-Printed',
      isReferenced: null
    },
    fabricCategory: {
      id: 1,
      modifiedAt: 1588750073064,
      lastModifiedBy: 'su_dev',
      name: 'Yarn Dyed',
      desc: null,
      uid: 'FabricCategory-Yarn Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 3,
    state: 'Pending',
    buyerPO: '3',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 3',
    styleColor: 'Windsurf Blue',
    fit: 'SLIM',
    fabArticle: 'ART-103',
    fabComposition: '97/3 Cotton Spandex ',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'NO',
    width: 144.78,
    repeatLength: 2.54,
    repeatWidth: 5.72,
    warpShrinkage: 1,
    weftShrinkage: 1,
    remarks: 'Test Remarks',
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":2},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Printed',
    millName: 'Arvind',
    sortField: 'SLIM-No-144.78-ALL OVER GARMENT-All garment one-way-1-1-2.54-5.72',
    repeats: '2.54 x 5.72',
    shrinkage: 'L+1.00% W+1.00'
  },
  {
    id: 29,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 1,
      modifiedAt: 1588750277792,
      lastModifiedBy: 'su_dev',
      name: 'Solid',
      desc: null,
      uid: 'FabricType-Solid',
      isReferenced: null
    },
    fabricCategory: {
      id: 2,
      modifiedAt: 1588750085099,
      lastModifiedBy: 'su_dev',
      name: 'Piece Dyed',
      desc: null,
      uid: 'FabricCategory-Piece Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 2,
    state: 'New',
    buyerPO: '2',
    internalPO: null,
    label: 'S1',
    styleName: 'Style 2',
    styleColor: 'White',
    fit: 'CLASSIC',
    fabArticle: 'ART-101',
    fabComposition: '97/3 Cotton/Spandex',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 129.54,
    repeatLength: null,
    repeatWidth: null,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: null,
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":1},"L":{"serial":3,"qty":2},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Solid',
    millName: 'Arvind',
    sortField: 'CLASSIC-No-129.54-ALL OVER GARMENT-All garment one-way-3-3-0-0',
    repeats: '',
    shrinkage: 'L+3.00% W+3.00'
  },
  {
    id: 28,
    mill: {
      id: 1,
      modifiedAt: 1588750364541,
      lastModifiedBy: 'su_dev',
      name: 'Arvind',
      desc: null,
      uid: 'Mill-Arvind',
      isReferenced: null
    },
    fabricType: {
      id: 4,
      modifiedAt: 1588750296825,
      lastModifiedBy: 'su_dev',
      name: 'Printed',
      desc: null,
      uid: 'FabricType-Printed',
      isReferenced: null
    },
    fabricCategory: {
      id: 2,
      modifiedAt: 1588750085099,
      lastModifiedBy: 'su_dev',
      name: 'Piece Dyed',
      desc: null,
      uid: 'FabricCategory-Piece Dyed',
      isReferenced: null
    },
    cstPart: null,
    estPart: null,
    itemNo: 1,
    state: 'Pending',
    buyerPO: '1',
    internalPO: null,
    label: 'NAUTICA',
    styleName: 'Style 1',
    styleColor: 'Gunsmoke Heather',
    fit: 'CLASSIC',
    fabArticle: 'ART-100',
    fabComposition: '100% Cotton',
    fabPlacement: 'ALL OVER GARMENT',
    fabDirection: 'All garment one-way',
    csv: 'No',
    wash: 'Yes',
    width: 144.78,
    repeatLength: 12.83,
    repeatWidth: 12.34,
    warpShrinkage: 3,
    weftShrinkage: 3,
    remarks: 'Test Remarks',
    sizeBreakup: '{"S":{"serial":1,"qty":1},"XL":{"serial":4,"qty":2},"2XL":{"serial":5,"qty":1},"L":{"serial":3,"qty":2},"M":{"serial":2,"qty":2}}',
    total: null,
    millId: 1,
    fabricTypeId: null,
    fabricCategoryId: null,
    buyerId: null,
    seasonId: null,
    cuChecklistId: null,
    costingId: null,
    estimationId: null,
    garmentTypeId: null,
    fabType: 'Printed',
    millName: 'Arvind',
    sortField: 'CLASSIC-No-144.78-ALL OVER GARMENT-All garment one-way-3-3-12.83-12.34',
    repeats: '12.83 x 12.34',
    shrinkage: 'L+3.00% W+3.00'
  }
]
